image: docker:latest
services:
  - docker:dind

stages:
  - build_latest

before_script:
  - echo Logging in to $CI_REGISTRY...
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  - docker info | grep Registry

build_latest:
  stage: build_latest
  script:
    - echo Build started on `date` for $CI_COMMIT_REF_NAME
    - docker build -t richarvey/boinc:latest .
    - docker images
    - docker push "$CI_REGISTRY_IMAGE":latest
  only:
    - master
